
// Groups:
// 0 : networks
// 1 : bridges
// 2 : swappers
// 3 : lend&borrow
// 4 : manage
// 5 : oracle
// 6 : wallets
// 7 : token (stables?)
// 8 :


// { id: "", group: 0, label: "", level: 1,
//   imgOnline:'',
//   url:'https://',
//   graphUrl:'' ,
//   query:'' , search:'' },


export const nodes = [
// NETWORKS
  { id: "ethereum", group: 0, label: "Ethereum", level: 1,
    imgOnline:'https://assets.coingecko.com/coins/images/279/thumb/ethereum.png?1595348880',
    url:'https://www.ethereum.org',
    explorer:'https://blockchair.com/bitcoin/',
    graphUrl:'' ,
    query:'' , search:'' },
  { id: "bitcoin", group: 0, label: "Bitcoin", level: 1,
    imgOnline:'https://assets.coingecko.com/coins/images/1/small/bitcoin.png?1547033579',
    url:'https://bitcoin.org',
    explorer:'https://etherscan.org',
    graphUrl:'' ,
    query:'' , search:'' },
  { id: "xdai", group: 0, label: "xDai", level: 1,
    imgOnline:'https://assets.coingecko.com/coins/images/11062/small/xdai.png?1614727492' ,
    url:'https://www.xdaichain.com',
    explorer:'https://blockscout.com',
    graphUrl:'' ,
    query:'' , search:''},
  { id: "polygon"  , group: 0, label: "Polygon"   , level: 1,
    imgOnline:'https://assets.coingecko.com/coins/images/4713/small/matic___polygon.jpg?1612939050' ,
    url:'https://www.polygon.com',
    contract:'0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0',
    explorer:'https://explorer-mainnet.maticvigil.com/',
    graphUrl:'' ,
    query:'' , search:''},
  { id: "binance-coin", group: 0, label: "BSC", level: 1,
    imgOnline:'https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615',
    url:'https://www.binance.com',
    explorer:'https://bscscan.com/',
    graphUrl:'' ,
    query:'' , search:'' },
//BRIDGES
  { id: "omnibridge"   , group: 1, label: "Omnibridge", level: 2,
    imgOnline:'https://omni.xdaichain.com/static/media/logo.5f96ff42.svg' ,
    url:'https://https://omni.xdaichain.com/',
    contract:'',
    graphUrl:'https://api.thegraph.com/subgraphs/name/raid-guild/xdai-omnibridge' ,
    query:'' , search:''},
  { id: "connext"   , group: 1, label: "Connext"   , level: 2,
    imgOnline:'https://connext.network/images/connext__Logo--WhiteText-MultiColor-p-500.png' ,
    url:'https://connext.network',
    contract:'',
    graphUrl:'' ,
    query:'' , search:''},
  { id: "pos-bridge"   , group: 1, label: "POS Bridge", level: 2,
    imgOnline:'https://docs.matic.network/img/logo.svg' ,
    url:'https://wallet.matic.network',
    contract:'',
    graphUrl:'' ,
    query:'' , search:''},
  { id: "wrapped-bitcoin", group: 1, label: "Wrapped BTC", level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/7598/small/wrapped_bitcoin_wbtc.png?1548822744',
    url:'https://wbtc.network',
    contract:'0x2260fac5e5542a773aa44fbcfedf7c193bc2c599',
    graphUrl:'' ,
    query:'' , search:'' },

// DAPPS
  { id: "aave"   , group: 3, label: "Aave" , level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png?1601374110' ,
    url:'https://aave.com',
    contract:'0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
    graphUrl:'' ,
    query:'' , search:''},
  { id: "uniswap"   , group: 2, label: "Uniswap"   , level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/12504/thumb/uniswap-uni.png?1600306604' ,
    url:'https://app.uniswap.org',
    contract:'',
    graphUrl:'https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2' ,
    query:'' , search:''},
  { id: "tether", group: 7, label: "Tether", level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/325/small/Tether-logo.png?1598003707',
    url:'https://tether.to',
    contract:'',
    graphUrl:'' ,
    query:'' , search:'' },
  { id: "usd-coin", group: 7, label: "USDC", level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/6319/small/USD_Coin_icon.png?1547042389',
    url:'https://circle.com',
    contract:'0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    graphUrl:'' ,
    query:'' , search:'' },
  { id: "honey" , group: 2, label: "Honeyswap", level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/12895/small/hnys.png?1614100588' ,
    url:'https://app.honeyswap.org',
    contract:'0x71850b7e9ee3f13ab46d67167341e4bdc905eef9', //xdai!
    graphUrl:'' ,
    query:'' , search:''},
  { id: "agave-token", group: 3, label: "Agave"   , level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/14146/thumb/agve.png?1614659384' ,
    url:'no ui yet',
    contract:'0x3a97704a1b25f08aa230ae53b352e2e72ef52843',//xdai!
    graphUrl:'' ,
    query:'' , search:''},
  { id: "aave-Matic"  , group: 3, label: "Aave-Matic"   , level: 2 ,
    imgOnline:'https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png?1601374110',
    url:'no ui yet',
    contract:'',
    graphUrl:'' ,
    query:'' , search:''},
  { id: "quickswap"  , group: 2, label: "Quickswap"  , level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/13970/small/1_pOU6pBMEmiL-ZJVb0CYRjQ.png?1613386659' ,
    url:'https://quickswap.exchange/#/swap',
    contract:'',
    graphUrl:'' ,
    query:'' , search:''},
  { id: "chainlink", group: 5, label: "Chainlink", level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png?1547034700',
    url:'https://chain.link',
    contract:'0x514910771af9ca656af840dff83e8264ecf986ca',
    graphUrl:'' ,
    query:'' , search:'' },
  { id: "binance-usd", group: 7, label: " Binance USD", level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/9576/small/BUSD.png?1568947766',
    url:'https://paxos.com',
    contract:'0x4fabb145d64652a948d72533023f6e7a623c7c53',
    graphUrl:'' ,
    query:'' , search:'' },
  { id: "pancakeswap", group: 2, label: "Pancake Swap", level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/12632/small/IMG_0440.PNG?1602654093',
    url:'https://pancakeswap.finance',
    contract:'0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82', //BSC!!
    graphUrl:'' ,
    query:'' , search:'' },
  { id: "dai", group: 7, label: "Dai", level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/9956/small/dai-multi-collateral-mcd.png?1574218774',
    url:'https://makerdao.com',
    contract:'0x6b175474e89094c44da98b954eedeac495271d0f',
    graphUrl:'',
    query:'' , search:'' },
  { id: "maker", group: 7, label: "Maker", level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/1364/small/Mark_Maker.png?1585191826',
    url:'https://makerdao.com',
    contract:'0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2',
    graphUrl:'' ,
    query:'' , search:'' },
  { id: "sushi", group: 2, label: "Sushi swap", level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/12271/small/512x512_Logo_no_chop.png?1606986688',
    url:'https://sushiswap.org',
    contract:'0x6b3595068778dd592e39a122f4f5a5cf09c90fe2',
    graphUrl:'' ,
    query:'' , search:'' },
  { id: "zapper", group: 4, label: "Zapper", level: 2,
    imgOnline:'https://dappimg.com/media/image/dapp/0a7290e46b8b47b09d7b26084fa9e0d2.blob',
    url:'https://zapper.fi',
    contract:'',
    graphUrl:'' ,
    query:'' , search:'' },
  { id: "zeroswap", group: 1, label: "Zeroswap", level: 2,
    imgOnline:'https://assets.coingecko.com/coins/images/12861/small/zeroswap.jpg?1603111827',
    url:'https://zeroswap.io',
    contract:'0x2edf094db69d6dcd487f1b3db9febe2eec0dd4c5',
    graphUrl:'' ,
    query:'' , search:'' },
  { id: "omnibridge_BSC", group: 1, label: "Omnibridge BSC-xDai", level: 2,
    imgOnline:'https://gblobscdn.gitbook.com/spaces%2F-LqBAx7LVGL5AF3NuAYj%2Favatar.png?alt=media',
    url:'https://bsc-to-xdai-omnibridge.web.app/  ',
    contract:'0x162E898bD0aacB578C8D5F8d6ca588c13d2A383F', //xdai - bsc:0x05185872898b6f94AA600177EF41B9334B1FA48B
    graphUrl:'' ,
    query:'' , search:'' },
        // { id: "", group: 0, label: "", level: 2,
        //   imgOnline:'',
        //   url:'https://',
        //   contract:'',
        //   graphUrl:'' ,
        //   query:'' , search:'' },
        //   { id: "", group: 0, label: "", level: 2,
        //     imgOnline:'',
        //     url:'https://',
        //     contract:'',
        //     graphUrl:'' ,
        //     query:'' , search:'' },


];
// graphurl : theGraph endpoint
// search: schema retrieved (for filter)
// query : query to thegraph (make particular queries for any need or total for user interaction)

export const links = [
  { target: "ethereum", source: "omnibridge" , strength: 0.7 },
  { target: "ethereum", source: "aave" , strength: 0.4 },
  { target: "ethereum", source: "uniswap" , strength: 0.4 },
  { target: "ethereum", source: "pos-bridge" , strength: 0.7 },
  { target: "ethereum", source: "tether" , strength: 0.4 },
  { target: "ethereum", source: "chainlink" , strength: 0.4 },
  { target: "ethereum", source: "wrapped-bitcoin" , strength: 0.4 },
  { target: "ethereum", source: "usd-coin" , strength: 0.4 },
  { target: "ethereum", source: "binance-usd" , strength: 0.4 },
  { target: "ethereum", source: "dai" , strength: 0.4 },
  { target: "ethereum", source: "maker" , strength: 0.4 },
  { target: "ethereum", source: "sushi" , strength: 0.4 },
  { target: "ethereum", source: "zapper" , strength: 0.4 },
  { target: "ethereum", source: "zeroswap" , strength: 0.4 },
  { target: "ethereum", source: "connext" , strength: 0.4 },
  { target: "maker", source: "dai" , strength: 0.4 },
  { target: "bitcoin", source: "wrapped-bitcoin" , strength: 0.4 },
  { target: "xdai", source: "honey" , strength: 0.7 },
  { target: "xdai", source: "agave-token" , strength: 0.4 },
  { target: "xdai", source: "omnibridge" , strength: 0.4 },
  { target: "xdai"  , source: "connext", strength: 0.7 },
  { target: "xdai", source: "chainlink" , strength: 0.4 },
  { target: "xdai", source: "omnibridge_BSC" , strength: 0.4 },
  { target: "polygon"  , source: "aave-Matic", strength: 0.4 },
  { target: "polygon"  , source: "quickswap", strength: 0.4 },
  { target: "polygon"  , source: "pos-bridge", strength: 0.7 },
  { target: "polygon", source: "connext" , strength: 0.7 },
  { target: "polygon", source: "chainlink" , strength: 0.4 },
  { target: "polygon", source: "zapper" , strength: 0.4 },
  { target: "binance-coin", source: "binance-usd" , strength: 0.4 },
  { target: "binance-coin", source: "pancakeswap" , strength: 0.4 },
  { target: "binance-coin", source: "zapper" , strength: 0.4 },
  { target: "binance-coin", source: "chainlink" , strength: 0.4 },
  { target: "binance-coin", source: "zeroswap" , strength: 0.4 },
  { target: "binance-coin", source: "omnibridge_BSC" , strength: 0.4 },

];
